# Generated by Django 4.2.3 on 2023-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='voqt',
            field=models.TextField(),
        ),
    ]
